### ISSUE TITLE
feature req: Role based access control

### ISSUE THREAD

**Issue by gebrits** [hoxton-one/deepstream.io#13]
It seems currently permissions have to be set per each individual user. Access control based on roles would make management of these permissions a lot easier.

**Comment by bguiz** [comment]
@gebrits See this page: http://deepstream.io/tutorials/records.html

In the second example you have users which belong to `beatles` and `stones` groups. The groups could just as easily have been called roles. All you have to do to get roles is to modify `canPerformAction` to match the list of roles instead of the string comparison used in the example.

**Comment by yasserf** [comment]
@bguiz Thanks, that's exactly the recommended approach!
