### ISSUE TITLE
Why does we need deepstream.io?

### ISSUE THREAD

**Issue by sangcu** [hoxton-one/deepstream.io#21]
Hey there, you guys are doing a great job. I just curious what does deepstream.io at under the hood difference with socket.io or faye?

**Comment by yasserf** [comment]
Hey, thanks! We got a comparison page between various other technologies in the pipeline! Watch this space.

**Comment by hopewise** [comment]
Hello Yasserf, any updates for the comparison page?

**Comment by yasserf** [comment]
hey,

This issue was meant to have been moved to the deepstream.io-website repo. Created it now [here](https://github.com/hoxton-one/deepstream.io-website/issues/37).

Please feel free to add any points we should use to compare frameworks against. This issue has now been pushed to the top of the priority list so should be out quite soon.
