### ISSUE TITLE
Proprietary message format

### ISSUE THREAD

**Issue by sjmueller** [hoxton-one/deepstream.io#35]
I'm curious to know more about the reasoning and decision to create the [proprietary messaging format](http://deepstream.io/tutorials/message-structure.html) used by deepstream.io.  Were other formats like [MessagePack](http://msgpack.org/) or WAMP considered at any point?  Are there any specific advantages you can share?

**Comment by WolframHempel** [comment]
Hi @sjmueller,

this is an excellent question. When it came to choosing a protocol, we've spent a lot of time debating the pro's and con's of the various existing solutions. Our protocol needed to fulfill three main requirements.

- ***Be extremely lightweight*** We're coming from a financial background where it is common to send hundreds of price updates to clients in a matter of seconds. While the individual messages are small, there can be very many of them, so every bit of overhead from the protocol inflates the amount of data being sent exponentially.

- ***Be fast to parse*** Our parser needed to be able to digest large amounts of messages in little time. This is the case for e.g. JSON parsing as it is build into the language, but parsing large amounts of MsgPack strings on a js level takes a bit of time. 

- ***Support partial messages*** Especially on a TCP level it is possible for a message to be split across two (or more) packages. This means that our parser needed to be able to parse all messages that were completely received, but buffer partial ones and only parse them once the remaining parts arrive.

With all this in mind, why did we choose to build our own protocol and why did it turn out to be the way it did?

- ***parsing speed*** All our parser actually consists of is two split() calls. One to separate the messages from each other, one to separate the various parts of a message. We only care about data-types for user send data, e.g. for RPC calls or when setting a path on a record. Everything else is treated as a string. This makes deepstream's parsing faster than any existing solution, not because it is particularly clever, but because it does very little at all.

- ***message size*** Messages consist of a topic short code, an action and some data. The only thing that our protocol adds are separators between them and a character that tells deepstream where the message ends. Fields that contain typed data have one additional letter specifying the type - and similar to MsgPack we only use a single character to identify values like null, undefined, true, false etc.
Having said that, MsgPack does a great job at the same task and would have been a very valid choice. We've been tempted to use it, but had to decide against it for the third reason:

- ***partial parsing*** This is something where most open formats fall short. The JSON or MsgPack parser expects complete messages - and throws an error if it receives partial ones. Of course we could have done a pre-parsing step and only feed complete messages to the parser, but this is already half of our parsing done.

So what about WAMP?
----------------------------------------
Wamp is a great step towards standardizing real-time use-cases. So is RTMP, XMPP, MQTT, Bayeux or RTP - to name just a few. The truth is, that we're still quite far away from having an "http for realtime" - just as we're only just beginning to discover all the great things we can do with a truly realtime web. Wamp for example would have covered most of deepstream's event and RPC mechanism, but has no concept of records, delta-updates or authentication-messages. Of course I'd agree that one could argue the right thing to do in the spirit of open source would have been to contribute to an existing protocol, but presented with the choice of determining which protocol is going to be the next standard and slowing deepstream's development down by working around its limitations - or rolling our own, we've chosen the latter.

**Comment by sjmueller** [comment]
Wow, thanks for such a great answer @WolframHempel.  I'm sure others will appreciate these insights when evaluating deepstream; in fact it may be worthwhile to reuse in the docs at some point.

**Comment by WolframHempel** [comment]
Cheers, I'll add it as a footnote to the Message Structure page

**Comment by thedrow** [comment]
Please do.
