### ISSUE TITLE
Loading multiple records

### ISSUE THREAD

**Issue by opsb** [hoxton-one/deepstream.io#39]
The current API appears to only allow individual records to be loaded. If you want to run a search for instance you create a dynamic list which returns the record ids which you then use to load the records individually. Is there any way to do this in one step? 

The particular use case I'm thinking of is relationships between records, ideally I'd like to query rethinkdb for related records and have them all returned in one go and then subscribe to any changes.

**Comment by yasserf** [comment]
We unfortunately don't have an API to do that.

The reason we left that to the developer to implement is since we often only request a single record/a subset from a list.

On a side note, there is the [rethinkdb-search-provider](https://github.com/hoxton-one/deepstream.io-provider-search-rethinkdb), which creates the dynamic list ( incase you haven't stumbled across it ).

**Comment by yasserf** [comment]
Closing issue, feel free to reopen if you have any follow up questions!
