### ISSUE TITLE
Server accepts new clients after calling stop

### ISSUE THREAD

**Issue by Lalem001** [hoxton-one/deepstream.io#44]
After calling server.stop, and before `stopped` event, all clients are disconnected.

Some clients, however, immediately attempt to reconnect, and successfully do connect.

This prevents the server's `stopped` event from firing, and the process needs to be killed manually.

Any suggestions to resolve this issue?

**Comment by WolframHempel** [comment]
Sounds like a genuine bug, we should look into it. Thanks for posting

**Comment by Lalem001** [comment]
After a lot of searching I have come across [server-destroy](https://github.com/isaacs/server-destroy). Looks like it can accomplish the desired behavior.

Thoughts?

**Comment by yasserf** [comment]
Hey Latem,

Thanks for the recommendation, I used that library before and it does work well for ensuring all connections get closed correctly when closing a server. The same logic is already in the deepstream server, the problem here however was mainly in deepstream still allowing connections on close.

We have a PR open with a fix and is just missing an extra unit test to ensure the close event gets triggered.
