### ISSUE TITLE
Getting a field that is null returns an empty object

### ISSUE THREAD

**Issue by jwanglof** [hoxton-one/deepstream.io#50]
I have the RethinkDB-connector activated. If I set a field to null with Deepstream and then tries to get it, it returns an empty object instead of null.

Example:

    var record = deepstream.record.getRecord('user/1234');
    record.whenReady(function () {
      console.log(record.get()); // Output 1
      record.set('field', null);
      record.discard();
    });

    var record2 = deepstream.record.getRecord('user/1234');
    record2.whenReady(function () {
      console.log(record2.get());  // Output 2
      console.log(record2.get('field'));  // Output 3
      record2.discard();
    });

**Output 1**
`{id: 1234, field: 'aField', field2: 'anotherField'}`

**Output 2**
`{id: 1234, field: null, field2: 'anotherField'}`

**Output 3**
`{}`

**Comment by yasserf** [comment]
Hey @jwanglof,

Thanks for finding this issue. I have a feeling it's something to do with [JsonPath.prototype.getValue](https://github.com/hoxton-one/deepstream.io-client-js/blob/master/src/record/json-path.js#30).

Since if:

console.log(record2.get());  // Output 2
console.log(record2.get('field'));  // Output 3

are run sequentially and return 

{id: 1234, field: null, field2: 'anotherField'}
{}

That means the object conversion is happening only when .get( fieldName ) is used.

Will take a deeper look later today!

**Comment by yasserf** [comment]
Closing since this is a client issue

Raised a pr for hoxton-one/deepstream.io-client-js#36
